/**
 * Vendors WFCD's relic list into `packages/protocol` as build-time JSON.
 *
 *   bun scripts/vendor-relics.ts
 *
 * CHECKED IN: a relic list that changes between deploys is a bucket key that
 * changes between deploys.
 *
 * Three things the data turned out to be:
 *
 * 1. NO REFINEMENT-INDEPENDENT RELIC. Every entry is one (relic, refinement)
 *    pair, with the refinement in the name and the uniqueName. `RelicId` is
 *    the base; deriving it otherwise gives `…EBronze:radiant`, i.e. "Intact,
 *    radiant".
 *
 * 2. TWO RELICS SHARE A DISPLAY NAME. `Lith G12` exists twice with identical
 *    reward tables. A player only knows the printed name, so both must land in
 *    the same bucket — otherwise two holders queue side by side forever.
 *
 * 3. Eight entries are placeholders ("Axi Relic") with no refinement. Skipped.
 */

const SOURCE =
  "https://raw.githubusercontent.com/WFCD/warframe-items/master/data/json/Relics.json";

/** Shared by every relic, so it distinguishes nothing. Recorded, not lost. */
const PREFIX = "/Lotus/Types/Game/Projections/";

/** Their vocabulary, not ours. */
const SUFFIXES: Record<string, string> = {
  Bronze: "intact",
  Silver: "exceptional",
  Gold: "flawless",
  Platinum: "radiant",
};

const TIERS = ["lith", "meso", "neo", "axi", "requiem", "vanguard"] as const;

type WfcdRelic = {
  uniqueName: string;
  name: string;
  vaulted?: boolean;
};

type VendoredRelic = {
  id: string;
  name: string;
  tier: string;
  /** The wedge: what recruiting chat cannot fill. */
  vaulted: boolean;
  /** Empty for all but one relic. */
  aliases?: string[];
};

const res = await fetch(SOURCE);
if (!res.ok) {
  console.error(`could not fetch WFCD relics: ${res.status}`);
  process.exit(1);
}
const raw = (await res.json()) as WfcdRelic[];

const byName = new Map<string, { ids: Set<string>; vaulted: boolean; tier: string }>();
let skipped = 0;

for (const entry of raw) {
  const words = entry.name.split(" ");
  const refinementWord = words[words.length - 1] ?? "";
  const refinement = Object.values(SUFFIXES).find(
    (r) => r === refinementWord.toLowerCase(),
  );
  if (!refinement) {
    skipped += 1;
    continue;
  }

  const name = words.slice(0, -1).join(" ");
  const tier = (words[0] ?? "").toLowerCase();
  if (!TIERS.includes(tier as (typeof TIERS)[number])) {
    skipped += 1;
    continue;
  }

  const suffix = Object.keys(SUFFIXES).find((s) => entry.uniqueName.endsWith(s));
  if (!suffix) {
    skipped += 1;
    continue;
  }

  const id = entry.uniqueName.slice(PREFIX.length, entry.uniqueName.length - suffix.length);
  const existing = byName.get(name);
  if (existing) {
    existing.ids.add(id);
    // Understating availability sends someone to recruiting chat for a relic
    // this app could have filled.
    existing.vaulted = existing.vaulted && (entry.vaulted ?? false);
  } else {
    byName.set(name, { ids: new Set([id]), vaulted: entry.vaulted ?? false, tier });
  }
}

const relics: VendoredRelic[] = [];
let merged = 0;

for (const [name, info] of byName) {
  // Lexicographically first, so regenerating cannot silently move a bucket
  // key from one spelling to the other.
  const ids = [...info.ids].sort();
  const [canonical, ...aliases] = ids;
  if (aliases.length > 0) merged += 1;
  relics.push({
    id: canonical!,
    name,
    tier: info.tier,
    vaulted: info.vaulted,
    ...(aliases.length > 0 ? { aliases } : {}),
  });
}

relics.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

const out = {
  $comment: "GENERATED by scripts/vendor-relics.ts. Do not edit by hand.",
  source: SOURCE,
  generatedAt: new Date().toISOString().slice(0, 10),
  uniqueNamePrefix: PREFIX,
  refinementSuffixes: SUFFIXES,
  relics,
};

const target = new URL("../packages/protocol/src/relics.generated.json", import.meta.url);
await Bun.write(target, JSON.stringify(out, null, 2) + "\n");

const byTier = relics.reduce<Record<string, number>>((acc, r) => {
  acc[r.tier] = (acc[r.tier] ?? 0) + 1;
  return acc;
}, {});

console.log(`wrote ${relics.length} relics`);
console.log(`  by tier: ${JSON.stringify(byTier)}`);
console.log(`  vaulted: ${relics.filter((r) => r.vaulted).length}`);
console.log(`  merged duplicate names: ${merged}`);
console.log(`  skipped non-relic entries: ${skipped}`);
