/**
 * Vendors WFCD's relic list into `packages/protocol` as build-time JSON.
 *
 *   bun scripts/vendor-relics.ts
 *
 * The result is CHECKED IN. A build that reaches out to GitHub is a build that
 * fails when GitHub does, and a relic list that changes under you between
 * deploys is a bucket key that changes under you between deploys.
 *
 * Three things this has to reconcile, all discovered from the data rather than
 * assumed:
 *
 * 1. WFCD HAS NO REFINEMENT-INDEPENDENT RELIC. Every entry is one (relic,
 *    refinement) pair, with the refinement baked into both the name ("Axi A1
 *    Radiant") and the uniqueName (…ESilver / …EGold / …EBronze / …EPlatinum).
 *    Our `RelicId` is the base — the uniqueName with that suffix removed — and
 *    the refinement is ours. Deriving it any other way would produce ids like
 *    `T4VoidProjectionEBronze:radiant`, which says "Intact, radiant".
 *
 * 2. TWO RELICS CAN SHARE A DISPLAY NAME. `Lith G12` exists twice
 *    (SevagothPrimeD and SevagothPrimeE) with byte-identical reward tables — a
 *    WFCD artifact. This matters more than it looks: a player only ever knows
 *    the printed name, so two people each holding "Lith G12" must land in the
 *    SAME bucket. Keeping both ids would leave them queued forever, side by
 *    side, never matching. They are merged onto one canonical id and the
 *    alias is recorded rather than dropped.
 *
 * 3. Eight entries are generic placeholders ("Axi Relic", "Void Relic") with
 *    no refinement. They are not relics anyone holds, and they are skipped.
 */

const SOURCE =
  "https://raw.githubusercontent.com/WFCD/warframe-items/master/data/json/Relics.json";

/** Every relic uniqueName begins with this. It distinguishes nothing, so it is
 *  stripped from the id and recorded here so the original is recoverable. */
const PREFIX = "/Lotus/Types/Game/Projections/";

/** WFCD's suffix for each refinement. Their vocabulary, not ours. */
const SUFFIXES: Record<string, string> = {
  Bronze: "intact",
  Silver: "exceptional",
  Gold: "flawless",
  Platinum: "radiant",
};

const TIERS = ["lith", "meso", "neo", "axi", "requiem", "vanguard"] as const;

type WfcdRelic = {
  uniqueName: string;
  name: string;
  vaulted?: boolean;
};

type VendoredRelic = {
  id: string;
  name: string;
  tier: string;
  /** The wedge: rare and vaulted relics are what recruiting chat cannot fill. */
  vaulted: boolean;
  /** Other WFCD ids that print the same name. Empty for all but one relic. */
  aliases?: string[];
};

const res = await fetch(SOURCE);
if (!res.ok) {
  console.error(`could not fetch WFCD relics: ${res.status}`);
  process.exit(1);
}
const raw = (await res.json()) as WfcdRelic[];

const byName = new Map<string, { ids: Set<string>; vaulted: boolean; tier: string }>();
let skipped = 0;

for (const entry of raw) {
  const words = entry.name.split(" ");
  const refinementWord = words[words.length - 1] ?? "";
  const refinement = Object.values(SUFFIXES).find(
    (r) => r === refinementWord.toLowerCase(),
  );
  if (!refinement) {
    skipped += 1;
    continue;
  }

  const name = words.slice(0, -1).join(" ");
  const tier = (words[0] ?? "").toLowerCase();
  if (!TIERS.includes(tier as (typeof TIERS)[number])) {
    skipped += 1;
    continue;
  }

  const suffix = Object.keys(SUFFIXES).find((s) => entry.uniqueName.endsWith(s));
  if (!suffix) {
    skipped += 1;
    continue;
  }

  const id = entry.uniqueName.slice(PREFIX.length, entry.uniqueName.length - suffix.length);
  const existing = byName.get(name);
  if (existing) {
    existing.ids.add(id);
    // Vaulted if ANY spelling of it is. Understating availability would send
    // someone to recruiting chat for a relic this app could have filled.
    existing.vaulted = existing.vaulted && (entry.vaulted ?? false);
  } else {
    byName.set(name, { ids: new Set([id]), vaulted: entry.vaulted ?? false, tier });
  }
}

const relics: VendoredRelic[] = [];
let merged = 0;

for (const [name, info] of byName) {
  // Canonical id is the lexicographically first, so regenerating the file
  // cannot silently move a bucket key from one spelling to the other.
  const ids = [...info.ids].sort();
  const [canonical, ...aliases] = ids;
  if (aliases.length > 0) merged += 1;
  relics.push({
    id: canonical!,
    name,
    tier: info.tier,
    vaulted: info.vaulted,
    ...(aliases.length > 0 ? { aliases } : {}),
  });
}

relics.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

const out = {
  $comment: "GENERATED by scripts/vendor-relics.ts. Do not edit by hand.",
  source: SOURCE,
  generatedAt: new Date().toISOString().slice(0, 10),
  uniqueNamePrefix: PREFIX,
  refinementSuffixes: SUFFIXES,
  relics,
};

const target = new URL("../packages/protocol/src/relics.generated.json", import.meta.url);
await Bun.write(target, JSON.stringify(out, null, 2) + "\n");

const byTier = relics.reduce<Record<string, number>>((acc, r) => {
  acc[r.tier] = (acc[r.tier] ?? 0) + 1;
  return acc;
}, {});

console.log(`wrote ${relics.length} relics`);
console.log(`  by tier: ${JSON.stringify(byTier)}`);
console.log(`  vaulted: ${relics.filter((r) => r.vaulted).length}`);
console.log(`  merged duplicate names: ${merged}`);
console.log(`  skipped non-relic entries: ${skipped}`);
